// GENERATED by scripts/gen-mcp-secret-patterns.mjs — DO NOT EDIT.
// Source: tests/fixtures/mcp/secret-patterns.json (the repo-root vectors both languages read).
// Run `bun run gen:mcp-patterns` after editing the source; `bun run check` fails on drift.

/** One named credential shape, as ECMAScript regex SOURCE (unanchored, case-sensitive). */
export interface SecretPattern {
  name: string;
  regex: string;
}

export const SECRET_PATTERNS: readonly SecretPattern[] = [
  { name: "github-token", regex: "gh[pousr]_[A-Za-z0-9]{36,255}" },
  { name: "github-fine-grained-token", regex: "github_pat_[A-Za-z0-9_]{22,255}" },
  { name: "openai-style-key", regex: "sk-[A-Za-z0-9_-]{20,}" },
  { name: "stripe-live-key", regex: "sk_live_[A-Za-z0-9]{16,}" },
  { name: "stripe-test-key", regex: "sk_test_[A-Za-z0-9]{16,}" },
  { name: "slack-token", regex: "xox[bp]-[A-Za-z0-9-]{10,}" },
  { name: "aws-access-key-id", regex: "AKIA[0-9A-Z]{16}" },
  { name: "gitlab-token", regex: "glpat-[A-Za-z0-9_-]{16,}" },
  { name: "google-oauth-access-token", regex: "ya29\\.[A-Za-z0-9_-]{20,}" },
  { name: "google-api-key", regex: "AIza[0-9A-Za-z_-]{35}" },
  { name: "bearer-credential", regex: "Bearer\\s+[A-Za-z0-9._~+/-]{20,}=*" },
];

/** The heuristic belt below the named shapes — see app/lib/mcp/validate.server.ts. */
export const SECRET_ENTROPY = {
  minLength: 24,
  threshold: 4.2,
} as const;
