-- THE CATALOG'S FIRST ROWS — the live-verified servers this install starts knowing about,
-- carried over from the list that used to live in code. Each becomes one global `mcp_server`
-- (workspace_id null) plus ONE published revision holding the document it stands for, in the
-- official registry format.
--
-- The editorial half travels with them and is the point: `auth_mode` is what a live check of the
-- vendor's own discovery chain concluded, not what the vendor claims, and every `manual` row
-- carries the one line saying what the person has to do first. The same word also rides the
-- document's `_meta`, so a machine reading the bytes and a person reading the row are told the
-- same thing.
--
-- Ids are DETERMINISTIC here (`mcps_<slug>` / `mcpr_<slug>_1`) so this file is re-readable and
-- the backfill beside it can match against rows it did not mint. Everything minted later is
-- random, like every other id in this schema.
--
-- The pointer move is its own statement at the end: a server's `current_revision_id` cannot name
-- a revision that does not exist yet, and a revision cannot name a server that does not either.

INSERT INTO "web"."mcp_server"
  (id, registry_name, display_name, description, icon, auth_mode, auth_note, status)
SELECT v.id, v.registry_name, v.display_name, v.description, v.icon, v.auth_mode, v.auth_note, 'active'
FROM (VALUES
  ('mcps_airtable', 'com.airtable/mcp', 'Airtable', 'Bases, tables and records in Airtable.', 'airtable', 'oauth', NULL),
  ('mcps_alpha-vantage', 'co.alphavantage/mcp', 'Alpha Vantage', 'Market data and financial indicators from Alpha Vantage.', NULL, 'oauth', NULL),
  ('mcps_amplitude', 'com.amplitude/mcp-server', 'Amplitude', 'Product analytics in Amplitude.', NULL, 'oauth', NULL),
  ('mcps_apify', 'com.apify/mcp', 'Apify', 'Run scrapers and automation actors on Apify.', NULL, 'oauth', NULL),
  ('mcps_asana', 'com.asana/mcp', 'Asana', 'Tasks, projects and portfolios in Asana.', 'asana', 'manual', 'Needs an OAuth app your admin registers with Asana — agents can''t sign in by themselves.'),
  ('mcps_atlassian', 'com.atlassian/atlassian-mcp-server', 'Atlassian', 'Jira issues and Confluence pages, through Atlassian''s Rovo server.', 'atlassian', 'oauth', NULL),
  ('mcps_aws-knowledge', 'com.amazon.aws/knowledge', 'AWS Knowledge', 'AWS documentation and API references.', NULL, 'none', NULL),
  ('mcps_bright-data', 'com.brightdata/mcp', 'Bright Data', 'Web data collection through Bright Data.', NULL, 'oauth', NULL),
  ('mcps_calendly', 'com.calendly/mcp', 'Calendly', 'Scheduling links and booked events in Calendly.', 'calendly', 'oauth', NULL),
  ('mcps_canva', 'com.canva/mcp', 'Canva', 'Designs, folders and brand assets in Canva.', NULL, 'oauth', NULL),
  ('mcps_clickup', 'com.clickup/mcp', 'ClickUp', 'Tasks, lists and docs in a ClickUp workspace.', 'clickup', 'oauth', NULL),
  ('mcps_cloudflare-docs', 'com.cloudflare.mcp/mcp', 'Cloudflare Docs', 'Search Cloudflare''s product documentation.', 'cloudflare', 'none', NULL),
  ('mcps_context7', 'com.context7/mcp', 'Context7', 'Up-to-date documentation and code examples for libraries.', NULL, 'none', NULL),
  ('mcps_datadog', 'com.datadoghq/mcp', 'Datadog', 'Metrics, monitors and incidents in Datadog.', 'datadog', 'oauth', NULL),
  ('mcps_deepwiki', 'com.deepwiki/mcp', 'DeepWiki', 'Ask questions about any public GitHub repository.', NULL, 'none', NULL),
  ('mcps_dropbox', 'com.dropbox/mcp', 'Dropbox', 'Files and folders in a Dropbox account.', 'dropbox', 'oauth', NULL),
  ('mcps_exa', 'ai.exa/exa', 'Exa', 'Semantic web search via Exa.', NULL, 'none', NULL),
  ('mcps_figma', 'com.figma.mcp/mcp', 'Figma', 'Design files, components and variables in Figma.', 'figma', 'oauth', NULL),
  ('mcps_firecrawl', 'dev.firecrawl/mcp', 'Firecrawl', 'Scrape and crawl web pages into clean, agent-readable text.', NULL, 'none', NULL),
  ('mcps_github', 'com.github/mcp', 'GitHub', 'Repositories, issues, pull requests and code search on GitHub.', 'github', 'manual', 'Needs a GitHub personal access token per person — agents can''t sign in by themselves.'),
  ('mcps_gitlab', 'com.gitlab/mcp', 'GitLab', 'Projects, issues and merge requests on GitLab.com.', 'gitlab', 'oauth', NULL),
  ('mcps_grafana', 'com.grafana/mcp', 'Grafana Cloud', 'Dashboards, datasources and alerts in Grafana Cloud.', 'grafana', 'oauth', NULL),
  ('mcps_heroku', 'com.heroku/mcp', 'Heroku', 'Apps, pipelines and add-ons on Heroku.', NULL, 'oauth', NULL),
  ('mcps_hugging-face', 'co.huggingface/hf-mcp-server', 'Hugging Face', 'Models, datasets and Spaces on the Hugging Face Hub.', 'huggingface', 'none', NULL),
  ('mcps_intercom', 'com.intercom/mcp', 'Intercom', 'Conversations, contacts and help articles in Intercom.', 'intercom', 'oauth', NULL),
  ('mcps_langsmith', 'com.langchain/langsmith', 'LangSmith', 'Traces, datasets and prompts in LangSmith.', 'langchain', 'oauth', NULL),
  ('mcps_linear', 'app.linear/linear', 'Linear', 'Issues, projects and cycles in Linear.', 'linear', 'oauth', NULL),
  ('mcps_microsoft-learn', 'com.microsoft.learn/mcp', 'Microsoft Learn', 'Search Microsoft and Azure technical documentation.', NULL, 'none', NULL),
  ('mcps_mixpanel', 'com.mixpanel/mcp', 'Mixpanel', 'Product analytics in Mixpanel.', 'mixpanel', 'oauth', NULL),
  ('mcps_monday', 'com.monday/monday.com', 'monday.com', 'Boards, items and docs in monday.com.', NULL, 'oauth', NULL),
  ('mcps_neon', 'tech.neon/mcp', 'Neon', 'Postgres projects, branches and queries on Neon.', 'neon', 'oauth', NULL),
  ('mcps_netlify', 'com.netlify/mcp', 'Netlify', 'Sites, deploys and build logs on Netlify.', 'netlify', 'oauth', NULL),
  ('mcps_new-relic', 'com.newrelic/mcp-server', 'New Relic', 'Telemetry, alerts and dashboards in New Relic.', 'newrelic', 'oauth', NULL),
  ('mcps_notion', 'com.notion/mcp', 'Notion', 'Pages, databases and comments in a Notion workspace.', 'notion', 'oauth', NULL),
  ('mcps_pagerduty', 'com.pagerduty/mcp', 'PagerDuty', 'Incidents, services and on-call schedules in PagerDuty.', 'pagerduty', 'manual', 'Needs a PagerDuty API token per person — agents can''t sign in by themselves.'),
  ('mcps_paypal', 'com.paypal.mcp/mcp', 'PayPal', 'Payments, invoices and orders in PayPal.', 'paypal', 'oauth', NULL),
  ('mcps_posthog', 'com.posthog/mcp', 'PostHog', 'Product analytics, feature flags and session replay in PostHog.', 'posthog', 'oauth', NULL),
  ('mcps_postman', 'com.postman/postman-mcp-server', 'Postman', 'Collections, APIs and workspaces in Postman.', 'postman', 'oauth', NULL),
  ('mcps_railway', 'com.railway/mcp', 'Railway', 'Services, deployments and logs on Railway.', 'railway', 'oauth', NULL),
  ('mcps_sanity', 'io.sanity.www/mcp', 'Sanity', 'Content, schemas and datasets in Sanity.', 'sanity', 'oauth', NULL),
  ('mcps_sentry', 'io.sentry/mcp', 'Sentry', 'Errors, issues and releases in Sentry.', 'sentry', 'oauth', NULL),
  ('mcps_slack', 'com.slack/mcp', 'Slack', 'Messages, channels and files in a Slack workspace.', NULL, 'manual', 'Needs a Slack app your admin registers — agents can''t sign in by themselves.'),
  ('mcps_square', 'com.squareup/mcp', 'Square', 'Payments, catalog and customers in Square.', 'square', 'oauth', NULL),
  ('mcps_stripe', 'com.stripe/mcp', 'Stripe', 'Customers, payments, subscriptions and invoices in Stripe.', 'stripe', 'oauth', NULL),
  ('mcps_supabase', 'com.supabase/mcp', 'Supabase', 'Projects, database schema and logs on Supabase.', 'supabase', 'oauth', NULL),
  ('mcps_tavily', 'com.tavily/mcp', 'Tavily', 'Web search and content extraction for agents via Tavily.', NULL, 'oauth', NULL),
  ('mcps_todoist', 'net.todoist/mcp', 'Todoist', 'Tasks and projects in Todoist.', 'todoist', 'oauth', NULL),
  ('mcps_vercel', 'com.vercel/vercel-mcp', 'Vercel', 'Projects, deployments and logs on Vercel.', 'vercel', 'oauth', NULL),
  ('mcps_webflow', 'com.webflow/mcp', 'Webflow', 'Sites, CMS collections and pages in Webflow.', 'webflow', 'oauth', NULL),
  ('mcps_wix', 'com.wix/mcp', 'Wix', 'Sites and business data in Wix.', 'wix', 'oauth', NULL)
) AS v (id, registry_name, display_name, description, icon, auth_mode, auth_note);
--> statement-breakpoint
INSERT INTO "web"."mcp_server_revision"
  (id, server_id, seq, status, upstream_version, schema_version, document, transport, url,
   source, published_at, published_by)
SELECT v.id, v.server_id, 1, 'published', v.upstream_version,
       'https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json',
       v.document, 'streamable-http', v.url, 'seed', now(), 'Topos'
FROM (VALUES
  ('mcpr_airtable_1', 'mcps_airtable', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.airtable/mcp","description":"Bases, tables and records in Airtable.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.airtable.com/mcp"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.airtable.com/mcp'),
  ('mcpr_alpha-vantage_1', 'mcps_alpha-vantage', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"co.alphavantage/mcp","description":"Market data and financial indicators from Alpha Vantage.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.alphavantage.co/mcp"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.alphavantage.co/mcp'),
  ('mcpr_amplitude_1', 'mcps_amplitude', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.amplitude/mcp-server","description":"Product analytics in Amplitude.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.amplitude.com/mcp"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.amplitude.com/mcp'),
  ('mcpr_apify_1', 'mcps_apify', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.apify/mcp","description":"Run scrapers and automation actors on Apify.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.apify.com/"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.apify.com/'),
  ('mcpr_asana_1', 'mcps_asana', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.asana/mcp","description":"Tasks, projects and portfolios in Asana.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.asana.com/v2/mcp"}],"_meta":{"sh.topos/auth":"manual"}}'::jsonb, 'https://mcp.asana.com/v2/mcp'),
  ('mcpr_atlassian_1', 'mcps_atlassian', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.atlassian/atlassian-mcp-server","description":"Jira issues and Confluence pages, through Atlassian''s Rovo server.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.atlassian.com/v1/mcp/authv2"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.atlassian.com/v1/mcp/authv2'),
  ('mcpr_aws-knowledge_1', 'mcps_aws-knowledge', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.amazon.aws/knowledge","description":"AWS documentation and API references.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://knowledge-mcp.global.api.aws"}],"_meta":{"sh.topos/auth":"none"}}'::jsonb, 'https://knowledge-mcp.global.api.aws'),
  ('mcpr_bright-data_1', 'mcps_bright-data', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.brightdata/mcp","description":"Web data collection through Bright Data.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.brightdata.com/mcp"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.brightdata.com/mcp'),
  ('mcpr_calendly_1', 'mcps_calendly', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.calendly/mcp","description":"Scheduling links and booked events in Calendly.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.calendly.com/"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.calendly.com/'),
  ('mcpr_canva_1', 'mcps_canva', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.canva/mcp","description":"Designs, folders and brand assets in Canva.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.canva.com/mcp"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.canva.com/mcp'),
  ('mcpr_clickup_1', 'mcps_clickup', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.clickup/mcp","description":"Tasks, lists and docs in a ClickUp workspace.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.clickup.com/mcp"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.clickup.com/mcp'),
  ('mcpr_cloudflare-docs_1', 'mcps_cloudflare-docs', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.cloudflare.mcp/mcp","description":"Search Cloudflare''s product documentation.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://docs.mcp.cloudflare.com/mcp"}],"_meta":{"sh.topos/auth":"none"}}'::jsonb, 'https://docs.mcp.cloudflare.com/mcp'),
  ('mcpr_context7_1', 'mcps_context7', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.context7/mcp","description":"Up-to-date documentation and code examples for libraries.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.context7.com/mcp"}],"_meta":{"sh.topos/auth":"none"}}'::jsonb, 'https://mcp.context7.com/mcp'),
  ('mcpr_datadog_1', 'mcps_datadog', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.datadoghq/mcp","description":"Metrics, monitors and incidents in Datadog.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.datadoghq.com/v1/mcp"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.datadoghq.com/v1/mcp'),
  ('mcpr_deepwiki_1', 'mcps_deepwiki', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.deepwiki/mcp","description":"Ask questions about any public GitHub repository.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.deepwiki.com/mcp"}],"_meta":{"sh.topos/auth":"none"}}'::jsonb, 'https://mcp.deepwiki.com/mcp'),
  ('mcpr_dropbox_1', 'mcps_dropbox', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.dropbox/mcp","description":"Files and folders in a Dropbox account.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.dropbox.com/mcp"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.dropbox.com/mcp'),
  ('mcpr_exa_1', 'mcps_exa', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"ai.exa/exa","description":"Semantic web search via Exa.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.exa.ai/mcp"}],"_meta":{"sh.topos/auth":"none"}}'::jsonb, 'https://mcp.exa.ai/mcp'),
  ('mcpr_figma_1', 'mcps_figma', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.figma.mcp/mcp","description":"Design files, components and variables in Figma.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.figma.com/mcp"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.figma.com/mcp'),
  ('mcpr_firecrawl_1', 'mcps_firecrawl', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"dev.firecrawl/mcp","description":"Scrape and crawl web pages into clean, agent-readable text.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.firecrawl.dev/mcp"}],"_meta":{"sh.topos/auth":"none"}}'::jsonb, 'https://mcp.firecrawl.dev/mcp'),
  ('mcpr_github_1', 'mcps_github', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.github/mcp","description":"Repositories, issues, pull requests and code search on GitHub.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://api.githubcopilot.com/mcp/"}],"_meta":{"sh.topos/auth":"manual"}}'::jsonb, 'https://api.githubcopilot.com/mcp/'),
  ('mcpr_gitlab_1', 'mcps_gitlab', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.gitlab/mcp","description":"Projects, issues and merge requests on GitLab.com.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://gitlab.com/api/v4/mcp"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://gitlab.com/api/v4/mcp'),
  ('mcpr_grafana_1', 'mcps_grafana', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.grafana/mcp","description":"Dashboards, datasources and alerts in Grafana Cloud.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.grafana.com/mcp"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.grafana.com/mcp'),
  ('mcpr_heroku_1', 'mcps_heroku', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.heroku/mcp","description":"Apps, pipelines and add-ons on Heroku.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.heroku.com/mcp"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.heroku.com/mcp'),
  ('mcpr_hugging-face_1', 'mcps_hugging-face', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"co.huggingface/hf-mcp-server","description":"Models, datasets and Spaces on the Hugging Face Hub.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://huggingface.co/mcp"}],"_meta":{"sh.topos/auth":"none"}}'::jsonb, 'https://huggingface.co/mcp'),
  ('mcpr_intercom_1', 'mcps_intercom', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.intercom/mcp","description":"Conversations, contacts and help articles in Intercom.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.intercom.com/mcp"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.intercom.com/mcp'),
  ('mcpr_langsmith_1', 'mcps_langsmith', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.langchain/langsmith","description":"Traces, datasets and prompts in LangSmith.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://api.smith.langchain.com/mcp"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://api.smith.langchain.com/mcp'),
  ('mcpr_linear_1', 'mcps_linear', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"app.linear/linear","description":"Issues, projects and cycles in Linear.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.linear.app/mcp"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.linear.app/mcp'),
  ('mcpr_microsoft-learn_1', 'mcps_microsoft-learn', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.microsoft.learn/mcp","description":"Search Microsoft and Azure technical documentation.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://learn.microsoft.com/api/mcp"}],"_meta":{"sh.topos/auth":"none"}}'::jsonb, 'https://learn.microsoft.com/api/mcp'),
  ('mcpr_mixpanel_1', 'mcps_mixpanel', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.mixpanel/mcp","description":"Product analytics in Mixpanel.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.mixpanel.com/mcp"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.mixpanel.com/mcp'),
  ('mcpr_monday_1', 'mcps_monday', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.monday/monday.com","description":"Boards, items and docs in monday.com.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.monday.com/mcp"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.monday.com/mcp'),
  ('mcpr_neon_1', 'mcps_neon', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"tech.neon/mcp","description":"Postgres projects, branches and queries on Neon.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.neon.tech/mcp"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.neon.tech/mcp'),
  ('mcpr_netlify_1', 'mcps_netlify', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.netlify/mcp","description":"Sites, deploys and build logs on Netlify.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://netlify-mcp.netlify.app/mcp"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://netlify-mcp.netlify.app/mcp'),
  ('mcpr_new-relic_1', 'mcps_new-relic', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.newrelic/mcp-server","description":"Telemetry, alerts and dashboards in New Relic.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.newrelic.com/mcp"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.newrelic.com/mcp'),
  ('mcpr_notion_1', 'mcps_notion', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.notion/mcp","description":"Pages, databases and comments in a Notion workspace.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.notion.com/mcp"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.notion.com/mcp'),
  ('mcpr_pagerduty_1', 'mcps_pagerduty', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.pagerduty/mcp","description":"Incidents, services and on-call schedules in PagerDuty.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.pagerduty.com/mcp"}],"_meta":{"sh.topos/auth":"manual"}}'::jsonb, 'https://mcp.pagerduty.com/mcp'),
  ('mcpr_paypal_1', 'mcps_paypal', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.paypal.mcp/mcp","description":"Payments, invoices and orders in PayPal.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.paypal.com/mcp"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.paypal.com/mcp'),
  ('mcpr_posthog_1', 'mcps_posthog', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.posthog/mcp","description":"Product analytics, feature flags and session replay in PostHog.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.posthog.com/mcp"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.posthog.com/mcp'),
  ('mcpr_postman_1', 'mcps_postman', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.postman/postman-mcp-server","description":"Collections, APIs and workspaces in Postman.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.postman.com/mcp"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.postman.com/mcp'),
  ('mcpr_railway_1', 'mcps_railway', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.railway/mcp","description":"Services, deployments and logs on Railway.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.railway.com/"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.railway.com/'),
  ('mcpr_sanity_1', 'mcps_sanity', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"io.sanity.www/mcp","description":"Content, schemas and datasets in Sanity.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.sanity.io"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.sanity.io'),
  ('mcpr_sentry_1', 'mcps_sentry', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"io.sentry/mcp","description":"Errors, issues and releases in Sentry.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.sentry.dev/mcp"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.sentry.dev/mcp'),
  ('mcpr_slack_1', 'mcps_slack', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.slack/mcp","description":"Messages, channels and files in a Slack workspace.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.slack.com/mcp"}],"_meta":{"sh.topos/auth":"manual"}}'::jsonb, 'https://mcp.slack.com/mcp'),
  ('mcpr_square_1', 'mcps_square', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.squareup/mcp","description":"Payments, catalog and customers in Square.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.squareup.com/mcp"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.squareup.com/mcp'),
  ('mcpr_stripe_1', 'mcps_stripe', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.stripe/mcp","description":"Customers, payments, subscriptions and invoices in Stripe.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.stripe.com"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.stripe.com'),
  ('mcpr_supabase_1', 'mcps_supabase', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.supabase/mcp","description":"Projects, database schema and logs on Supabase.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.supabase.com/mcp"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.supabase.com/mcp'),
  ('mcpr_tavily_1', 'mcps_tavily', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.tavily/mcp","description":"Web search and content extraction for agents via Tavily.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.tavily.com/mcp"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.tavily.com/mcp'),
  ('mcpr_todoist_1', 'mcps_todoist', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"net.todoist/mcp","description":"Tasks and projects in Todoist.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://ai.todoist.net/mcp"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://ai.todoist.net/mcp'),
  ('mcpr_vercel_1', 'mcps_vercel', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.vercel/vercel-mcp","description":"Projects, deployments and logs on Vercel.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.vercel.com"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.vercel.com'),
  ('mcpr_webflow_1', 'mcps_webflow', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.webflow/mcp","description":"Sites, CMS collections and pages in Webflow.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.webflow.com/mcp"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.webflow.com/mcp'),
  ('mcpr_wix_1', 'mcps_wix', '1.0.0', '{"$schema":"https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json","name":"com.wix/mcp","description":"Sites and business data in Wix.","version":"1.0.0","remotes":[{"type":"streamable-http","url":"https://mcp.wix.com/mcp"}],"_meta":{"sh.topos/auth":"oauth"}}'::jsonb, 'https://mcp.wix.com/mcp')
) AS v (id, server_id, upstream_version, document, url);
--> statement-breakpoint
UPDATE "web"."mcp_server" s
SET current_revision_id = r.id
FROM "web"."mcp_server_revision" r
WHERE r.server_id = s.id AND r.source = 'seed' AND r.seq = 1;
