/**
 * Generated by scripts/gen-plane-types.mjs from ../contracts/openapi/openapi.json — do not edit.
 * Regenerate with: bun run gen:plane
 */
export interface paths {
    "/v1/enroll/verify/{user_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["read_verification_context"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionCode
         * @description A machine-actionable next-action code. The values in `examples` are the known set; an unrecognized future code is still valid and MUST be executed via the action's `argv` (never rejected).
         * @example PROPOSE_PUBLISH
         * @example REBASE_AND_RETRY
         * @example RESOLVE_DIVERGED_DRAFT
         * @example APPLY_WAITING_UPDATE
         * @example DISAMBIGUATE_NAME
         * @example REQUEST_ACCESS
         * @example RETRY
         * @example CONTACT_ADMIN
         */
        ActionCode: string;
        /**
         * @description The disclosure a `publish` attaches when it ADDED the skill to topos before shipping — the auto-add
         *     convenience (`publish` accepts an untracked local source and adopts it first). Public disclosure only
         *     (the same facts an explicit `topos add` would return); never a secret. **INFERRED** (additive-only).
         */
        AddedNote: {
            /**
             * @description The harness registry slug the adopted directory was attributed to (e.g. `claude-code`), or `None`
             *     for a plain directory adopted in place under no known harness.
             */
            harness_slug?: string | null;
            /** @description The name the skill was adopted under (what `list` / `diff` / `publish` now resolve it by). */
            name: string;
        };
        /**
         * @description `POST /v1/admin-claim` body — consume a one-time self-host claim token to stand up a workspace + seat its
         *     first owner. The server re-derives the device key id from `device_public_key`.
         */
        AdminClaimRequest: {
            /** @description The one-time admin-claim token. */
            claim_token: string;
            /** @description The claiming device's raw 32-byte public key, base64url-unpadded. */
            device_public_key: string;
            /** @description The display name for the standing-up workspace. */
            display_name: string;
        };
        /** @description What an outcome refers to (every field optional — a policy flip has no skill/version). */
        Affected: {
            proposal?: string | null;
            skill?: string | null;
            /** @description A `version_id` (commit SHA-256, lowercase hex) when the outcome refers to a version. */
            version?: string | null;
            workspace?: string | null;
        };
        /**
         * @description The payload an `/i/<token>` invite link resolves to — read once, before enrollment, to learn the
         *     workspace + the plane API base to dial. No bytes, no role.
         */
        BootstrapData: {
            /** @description The invite's non-secret descriptor (consent posture, expiry). */
            invite: components["schemas"]["BootstrapInvite"];
            /**
             * @description The skills the invite pre-offers (a name may be absent → the client shows the id). Empty for a
             *     membership-only door.
             */
            offered_skills?: components["schemas"]["BootstrapSkill"][];
            /** @description The plane the workspace lives on — its API base and enrollment method. */
            plane: components["schemas"]["BootstrapPlane"];
            /**
             * Format: int32
             * @description Always `1` for this contract version (the schema pins it `const`).
             */
            schema_version: number;
            /** @description The workspace the invite is for. */
            workspace: components["schemas"]["BootstrapWorkspace"];
        };
        /** @description The invite's non-secret descriptor — the consent posture a redeemer agrees to, never a role. */
        BootstrapInvite: {
            /** @description The consent posture every first-receive follows. */
            consent: components["schemas"]["ConsentMode"];
            /** @description The invite's expiry as an RFC-3339 string, if it expires (`None` = never). */
            expires_at?: string | null;
            /**
             * @description Whether a first-received skill auto-lands. **ALWAYS false** — a received skill is offered, never
             *     silently applied (a direct human yes is required).
             */
            first_receive_auto_land: boolean;
            /**
             * @description A stable, non-secret reference for this invite (the link token the client used to reach the
             *     payload). Empty for an admin-claim bootstrap — a claim token is a live one-time bearer capability
             *     the server never echoes into a body; the claim client uses the token it parsed from the link.
             */
            token_id: string;
        };
        /** @description The plane a workspace lives on — its public base URL, deployment posture, and offered enrollment method. */
        BootstrapPlane: {
            /**
             * @description The plane's public API base URL — the root the client dials for enrollment and sync after this
             *     bootstrap read. Always the plane itself, never a web front: a share link may ride another host,
             *     but the client re-roots onto this value the moment the bootstrap is fetched.
             */
            base_url: string;
            /** @description This plane's deployment posture. */
            deployment_mode: components["schemas"]["DeploymentMode"];
            /** @description The enrollment method advertised to a bootstrapping device (e.g. `"device_code"` / `"passcode"`). */
            enrollment_method: string;
        };
        /**
         * @description One skill an invite pre-offers — its id, plus an optional display name (names ride the invite; a missing
         *     name means the client shows the id).
         */
        BootstrapSkill: {
            /** @description The skill's display name, if the invite carried one (else the client shows the id). */
            name?: string | null;
            /** @description The offered skill id. */
            skill_id: string;
        };
        /**
         * @description The workspace an invite is for — its id, display name, and domain-verification state. No role (the role
         *     lives server-side on the pre-seeded member rows).
         */
        BootstrapWorkspace: {
            /** @description The workspace display name (shown on the verification page + in the agent's disclosure). */
            display_name: string;
            /** @description The org-domain claim, if any. */
            verified_domain?: string | null;
            /** @description The domain-verification state. */
            verified_domain_status: components["schemas"]["VerifiedDomainStatus"];
            /** @description The workspace id. */
            workspace_id: string;
        };
        /**
         * @description The consent posture of an invite — a CLOSED set. v0 is a single mode: a received skill is disclosed and
         *     awaits a direct human yes on first receive (never auto-landed).
         * @enum {string}
         */
        ConsentMode: "direct_human_first_receive";
        CurrentRecord: {
            generation: components["schemas"]["Generation"];
            /**
             * @description The full commit SHA-256 (lowercase hex) — the `version_id`. NOT the `bundle_digest`: the
             *     pointer names the version, and the commit transitively pins the bytes.
             */
            version_id: string;
        };
        /**
         * @description A plane's deployment posture — a CLOSED set. `cloud` requires a confirmed identity step at enrollment;
         *     `self_host` grants membership straight from a valid grant.
         * @enum {string}
         */
        DeploymentMode: "cloud" | "self_host";
        /**
         * @description `POST /v1/device/authorize` body — begin an RFC-8628 device-authorization flow. With a `workspace`
         *     (the address name; the default `enroll` intent) the device enrolls toward that workspace; with
         *     `intent = "standup"` — or neither field — it starts a STANDUP session (no workspace yet; hosted
         *     planes only); with `intent = "login"` it starts a workspace-less LOGIN session whose grant redeems
         *     at `POST /v1/login`. The server SERVER-derives the device key id from `device_public_key` (a
         *     client-asserted id is never trusted).
         */
        DeviceAuthorizeRequest: {
            /**
             * @description The device's raw 32-byte public key, base64url-unpadded. The server derives the device key id from
             *     it (never a client-asserted id) and binds it to the enrollment session.
             */
            device_public_key: string;
            intent?: null | components["schemas"]["SessionIntent"];
            /** @description A human-readable machine name shown on the verification page (a confused-deputy guard, not authority). */
            machine_name: string;
            /**
             * @description The workspace ADDRESS name an enroll session targets (`topos.sh/<name>` minus the origin).
             *     Whether the name exists is never disclosed on this route: an unknown name runs the same flow to
             *     the same uniform denial a not-yours workspace gets.
             */
            workspace?: string | null;
        };
        /** @description `POST /v1/device/authorize` response — the RFC-8628 device-authorization grant (the names mirror the RFC). */
        DeviceAuthorizeResponse: {
            /** @description The SECRET device code the client polls `device/token` with. */
            device_code: string;
            /**
             * Format: int64
             * @description The session lifetime, in seconds (RFC-8628 `expires_in`).
             */
            expires_in: number;
            /**
             * Format: int64
             * @description The minimum poll interval, in seconds (RFC-8628 `interval`).
             */
            interval: number;
            plane?: null | components["schemas"]["BootstrapPlane"];
            /**
             * @description The opaque code identifying this device-auth session; it rides inside `verification_uri_complete`
             *     (the human clicks the URL — it is not typed).
             */
            user_code: string;
            /** @description The verification URL a human visits to approve the session. */
            verification_uri: string;
            /**
             * @description The verification URL with the user code already embedded (RFC-8628 `verification_uri_complete`) —
             *     the one link to open; a client uses it VERBATIM when present.
             */
            verification_uri_complete?: string | null;
        };
        /**
         * @description `DELETE /v1/workspaces/{ws}/devices` body — revoke a registered device key (owner, or the device's own
         *     principal). The revoke is INSTANT (flip `revoked` in one transaction — the row's credential stops
         *     authorizing fresh work the moment it commits).
         */
        DeviceRevokeRequest: {
            /** @description The client-minted UUIDv4 idempotency key. */
            op_id: string;
            /**
             * @description The id of the device key to revoke (the TARGET, named by its non-secret id; the actor rides the
             *     Bearer credential).
             */
            target_device_key_id: string;
            /** @description The target workspace id (scopes the op to one workspace). */
            workspace_id: string;
        };
        /** @description `POST /v1/device/token` body — poll a device-authorization session for its grant. */
        DeviceTokenRequest: {
            /** @description The SECRET device code from `device/authorize`. */
            device_code: string;
        };
        /**
         * @description `POST /v1/device/token` response — the poll `status`, plus the opaque single-use enrollment `grant` ONLY
         *     when `status` is `granted`. A re-poll of a confirmed session re-derives the SAME grant (idempotent issue).
         */
        DeviceTokenResponse: {
            /** @description The opaque single-use enrollment grant — present ONLY when `status` is `granted` (the redeem credential). */
            grant?: string | null;
            /** @description The poll status. */
            status: components["schemas"]["DeviceTokenStatus"];
            workspace?: null | components["schemas"]["DeviceTokenWorkspace"];
        };
        /**
         * @description A device-authorization poll status — the RFC-8628 outcomes (snake_case). `granted` carries the opaque
         *     grant; every other status carries only itself (no grant).
         * @enum {string}
         */
        DeviceTokenStatus: "pending" | "slow_down" | "denied" | "expired" | "granted";
        /**
         * @description The workspace context a `granted` poll carries — the id + display name a STANDUP client (which never
         *     read an `/i/` bootstrap) needs to build its redeem possession frame and disclose what it joined.
         */
        DeviceTokenWorkspace: {
            /**
             * @description The workspace's full ADDRESS (server-built on the public link base) — the share line's root;
             *     absent when the plane predates addresses or the grant is workspace-less.
             */
            address?: string | null;
            /** @description The workspace display name (a disclosure aid; `""` if the plane no longer has one). */
            display_name: string;
            /** @description The workspace the grant is scoped to. */
            workspace_id: string;
        };
        /**
         * @description The internal anti-replay counter `(epoch, seq)`. NEVER rendered to a user; the
         *     agent consumes `expected`/`current` on a CONFLICT.
         */
        Generation: {
            /** Format: int64 */
            epoch: number;
            /** Format: int64 */
            seq: number;
        };
        /**
         * @description `POST /v1/workspaces/{ws}/invitations` success `data` — what the inviter pastes onward: the workspace
         *     ADDRESS (the whole invitation besides the roster rows themselves).
         */
        InvitationData: {
            /** @description The workspace address (the share link — it carries nothing; the roster is the lock). */
            address: string;
            /** @description The emails now seated as invited members (canonical form). */
            invited: string[];
            /** @description Whether invitation mail was sent server-side (`true` only when the server can send mail). */
            mailed: boolean;
        };
        /**
         * @description `POST /v1/workspaces/{ws}/invitations` body — invitation as a ROSTER WRITE: seat each email as an
         *     invited member (recording who invited whom) and optionally pre-place the person into channels.
         *     There is no invite link and no role field — every CLI invitee starts as a member (roles are raised
         *     later, on the web), and joining is `follow <address>` plus proof of the invited email. Member-level
         *     unless the workspace's invite policy restricts inviting to owners.
         */
        InvitationRequest: {
            /**
             * @description Channel names to pre-place each invitee into (re-inviting restores placements; the structural
             *     `everyone` needs no placement and is accepted as a no-op).
             */
            channels?: string[];
            /** @description The emails to seat as invited members (folded to the canonical lowercase form server-side). */
            emails: string[];
        };
        /**
         * @description The one common envelope every verb emits. Never prompts; prose (TTY) is rendered from the
         *     SAME typed value where practical.
         */
        JsonEnvelope: {
            /** @description The verb that produced this (`add`, `follow`, `pull`, `list`, `publish`, …). */
            command: string;
            /** @description Command-specific payload (`{}` when empty). */
            data?: unknown;
            error?: null | components["schemas"]["WireError"];
            /** @description Stable, machine-actionable next steps — each carries a complete argv. */
            next_actions?: components["schemas"]["NextAction"][];
            ok: boolean;
            receipt?: null | components["schemas"]["Receipt"];
            /**
             * Format: int32
             * @description Always `1` for this contract version (the schema pins it `const`).
             */
            schema_version: number;
            warnings?: string[];
        };
        /** @description `POST /v1/login` success `data` — the proven identity + one entry per confirmed seat. */
        LoginData: {
            /** @description One entry per workspace where the principal holds a confirmed seat (possibly empty). */
            memberships: components["schemas"]["LoginMembership"][];
            /** @description The proven principal (canonical form). */
            principal: string;
        };
        /** @description One workspace a login re-minted (or could not re-mint) a credential for. */
        LoginMembership: {
            /** @description Why no credential was minted (e.g. this device is revoked in that workspace); absent on success. */
            blocked?: string | null;
            /**
             * @description The freshly minted plaintext workspace credential — absent when the mint was refused (see
             *     `blocked`). Returned ONCE; the server stores only its hash.
             */
            credential?: string | null;
            /** @description The device's non-secret key id in this workspace (server-derived). */
            device_key_id: string;
            /** @description The workspace's display name. */
            display_name: string;
            /** @description The workspace's ADDRESS name. */
            name: string;
            /** @description The person's role on the seat (`owner` / `reviewer` / `member`). */
            role: string;
            /** @description The workspace id. */
            workspace_id: string;
        };
        /**
         * @description `POST /v1/login` body — redeem a LOGIN grant: prove the device key the grant is bound to and
         *     receive one workspace credential per confirmed seat. The grant is the bearer credential; the
         *     device public key is a binding check (nothing signs).
         */
        LoginRedeemRequest: {
            /** @description The device's raw 32-byte public key, base64url-unpadded — must equal the grant's bound key. */
            device_public_key: string;
            /** @description The opaque grant from the login device flow (the bearer credential for this one exchange). */
            grant: string;
        };
        /**
         * @description A machine-actionable next step. The `argv` is the ready-to-exec command; `code` lets an agent
         *     branch on the known set and still pass through unknowns.
         */
        NextAction: {
            /** @description A complete argv array — execute as-is (no TTY parsing). */
            argv: string[];
            code: components["schemas"]["ActionCode"];
        };
        /**
         * @description `POST /v1/workspaces/{ws}/notices/ack` body — acknowledge notices by id (person-scoped read-state;
         *     the silent hook fetches without acking, an interactive narration acks what it narrated).
         */
        NoticeAckRequest: {
            /** @description The notice ids to mark read (only the caller's own unacked rows move; unknown ids are ignored). */
            ids: string[];
        };
        /**
         * @description `POST /v1/enroll/passcode` response — a CONSTANT-shaped ack (always `sent`); the send is fire-and-forget,
         *     so neither the body nor its latency reveals whether the address was rostered.
         */
        PasscodeAck: {
            /** @description Always `sent`. */
            status: components["schemas"]["PasscodeAckStatus"];
        };
        /**
         * @description The constant-shaped status of a started passcode challenge — always `sent`, so a non-rostered address is
         *     no enumeration oracle (the cloud roster gate is enforced at redeem, never here).
         * @enum {string}
         */
        PasscodeAckStatus: "sent";
        /** @description `POST /v1/enroll/passcode/confirm` body — submit a passcode to confirm the session's identity. */
        PasscodeConfirmRequest: {
            /** @description The 6-digit passcode the human entered. */
            code: string;
            /** @description The email the passcode was sent to. */
            email: string;
            /** @description The user code naming the live device-auth session. */
            user_code: string;
        };
        /** @description `POST /v1/enroll/passcode/confirm` response — the confirmation status. */
        PasscodeConfirmResponse: {
            /** @description The confirmation status. */
            status: components["schemas"]["PasscodeConfirmStatus"];
        };
        /**
         * @description The outcome of a passcode confirmation (snake_case). A wrong code carries only the status — never the
         *     attempts remaining (no brute-force timing/count oracle on the wire).
         * @enum {string}
         */
        PasscodeConfirmStatus: "confirmed" | "wrong_code" | "expired" | "too_many_attempts";
        /** @description `POST /v1/enroll/passcode` body — start a passcode challenge for an email on a live device-auth session. */
        PasscodeRequest: {
            /** @description The email the passcode proves control of. */
            email: string;
            /** @description The user code naming the live device-auth session. */
            user_code: string;
        };
        PointerScope: {
            skill_id: string;
            workspace_id: string;
        };
        /**
         * @description `PUT /v1/workspaces/{ws}/policy/review-required` body — the self-host operator toggle for the
         *     `review-required` workspace policy (an idempotent set; JSON so the body stays extensible without a
         *     path-shape change). Authenticated by the plane's admin token, not a device credential; the route is
         *     invisible (404) on a plane with no admin token configured.
         */
        PolicyReviewRequiredRequest: {
            /** @description The desired policy value: `true` gates any direct publish behind a reviewer's approval. */
            review_required: boolean;
        };
        /**
         * @description `publish --propose` (opens a PR; uploads a full candidate **without moving `current`**). Returns
         *     `NEEDS_REVIEW`. **INFERRED.**
         */
        ProposeData: {
            added?: null | components["schemas"]["AddedNote"];
            base_version_id: string;
            body?: string | null;
            /** @description `<skill>@<version_id>` of the candidate. */
            proposal: string;
            title: string;
        };
        /**
         * @description `POST /v1/proposals` body — opens a proposal (a PR): ingests a full candidate **without moving
         *     `current`** (`NEEDS_REVIEW`). The authority's `propose` op takes the **same** input shape as
         *     `publish` (candidate + device + `op_id` + `expected`); there is **no** separate title/body on the op (a
         *     title/body, if ever surfaced, would be composed into the candidate's commit message).
         */
        ProposeRequest: {
            /** @description The full candidate bundle to ingest as the proposal's content. */
            candidate: components["schemas"]["WireCandidate"];
            /**
             * @description The `--to` channel placement (same semantics as `PublishRequest.channel`): the placement
             *     applies when the proposal opens — a placement is curation, gated by the channel's mode,
             *     independent of the version's review.
             */
            channel?: string | null;
            /**
             * @description The skill's human display name (the author's skill-folder name) — ADVISORY metadata, carried for
             *     symmetry with [`PublishRequest`]. It rides the proposal but is never digested or part of the
             *     candidate; the plane records a name only when the pointer actually moves (a later approve/publish).
             */
            display_name?: string | null;
            /** @description The `(epoch, seq)` the proposal is born against (its base); a stale base later makes it non-current. */
            expected: components["schemas"]["Generation"];
            /** @description The client-minted UUIDv4 idempotency key (replays the stored receipt on retry). */
            op_id: string;
            /** @description The target skill id within the workspace. */
            skill_id: string;
            /** @description The target workspace id. */
            workspace_id: string;
        };
        /**
         * @description `PUT /v1/workspaces/{ws}/skills/{skill}/protection` and
         *     `PUT /v1/workspaces/{ws}/channels/{ch}/protection` body — the safety knob. Levels are per kind:
         *     `reviewed`/`open` for a skill bundle, `curated`/`open` for a channel. Tightening takes reviewer+;
         *     loosening back to `open` takes an owner.
         */
        ProtectionSetRequest: {
            /** @description The target level (`open`, `reviewed` for skills, `curated` for channels). */
            level: string;
        };
        /**
         * @description `publish` (a direct publish that moves `current`). On a GENESIS (first) publish the client also folds in
         *     a shareable `/i/` link pre-offering the skill — **best-effort + owner-gated** (minting it signs a
         *     governance op the plane denies for a non-owner), so `invite_link` is `Some` only on a genesis publish by
         *     an owner, and `None` otherwise. Under `review-required` a direct publish instead returns
         *     `APPROVAL_REQUIRED` (with the `publish --propose` next-action) and carries no `data`. **INFERRED.**
         *
         *     An UN-ENROLLED direct publish on the hosted plane starts a workspace STANDUP instead of failing: the
         *     envelope is still `ok = true`, but `data` carries the [`PublishPending`] block (sign in to approve) and
         *     no version — `version_id` / `current_generation` are `None` at pending because nothing was published yet
         *     (only the computed digest of the bytes being published can be honestly filled). Re-invoking the SAME
         *     publish command (the `ENROLL_RESUME` next-action) resumes: once the sign-in is approved, the same command
         *     completes enrollment AND the publish in one invocation, and the receipt carries the [`StandupReceipt`]
         *     disclosure.
         */
        PublishData: {
            added?: null | components["schemas"]["AddedNote"];
            /**
             * @description The byte-exact digest of the shipped (or, at pending, the scanned) bytes — always present: it is
             *     computed over the draft before any network call, and an optional `<skill>@<digest>` pin gates it.
             */
            bundle_digest: string;
            current_generation?: null | components["schemas"]["Generation"];
            pending?: null | components["schemas"]["PublishPending"];
            /**
             * @description The paste-able share line for the shipped skill (`<workspace address>/skills/<name>`) — present
             *     when the plane disclosed the workspace address. The pointer move is the real outcome; the line is
             *     what a human pastes in chat.
             */
            share_line?: string | null;
            skill_id: string;
            standup?: null | components["schemas"]["StandupReceipt"];
            /**
             * @description The new commit — `None` while the publish is PENDING a workspace-standup sign-in (nothing was
             *     published yet; the version id is only knowable once the bytes actually ship).
             */
            version_id?: string | null;
        };
        /** @description The workspace-standup sign-in a pending `publish` waits on. **INFERRED.** */
        PublishPending: {
            /** @description 16-hex fingerprint of this device's public key; a human cross-checks it against the sign-in page. */
            device_fingerprint: string;
            /** @description The sign-in session's expiry as an RFC-3339 string, if it expires. */
            expires_at?: string | null;
            /** @description Always `signin_required` — the one pending state this block discloses. */
            status: components["schemas"]["PublishPendingStatus"];
            /** @description The code embedded in the URL, shown for cross-checking on the sign-in page. */
            user_code: string;
            /**
             * @description The sign-in URL with the code already embedded — the ONE link a human opens to approve (served by
             *     the plane; the client uses it verbatim).
             */
            verification_uri_complete: string;
        };
        /**
         * @description A pending publish's status — a CLOSED single-value set (snake_case): the standup sign-in is required.
         * @enum {string}
         */
        PublishPendingStatus: "signin_required";
        /**
         * @description `POST /v1/publish` body — a direct publish that moves `current`. The acting device rides the
         *     `Authorization: Bearer` workspace credential (resolved in-transaction to its registry row + the
         *     membership gate); the server stamps `created_at`.
         *     Under `review-required` the authority refuses this closed with `APPROVAL_REQUIRED`, ingesting nothing.
         */
        PublishRequest: {
            /** @description The full candidate bundle to ingest + publish. */
            candidate: components["schemas"]["WireCandidate"];
            /**
             * @description The `--to` channel placement: place the skill's reference into this channel (created on first
             *     use, member-level; a `curated` channel needs reviewer+ — the placement outcome rides the
             *     receipt's details, independently of the version gate). Absent ⇒ no explicit placement (a
             *     brand-new skill still lands in `everyone`).
             */
            channel?: string | null;
            /**
             * @description The skill's human display name (the author's skill-folder name) — ADVISORY metadata the plane
             *     stores last-writer-wins and serves for display only (a follower names its folder by it; the
             *     dashboard shows it). It is NOT part of the byte-exact bundle digest, the candidate, or the commit
             *     id — a rename never changes a version id or digest. Absent ⇒ the plane keeps any existing name
             *     (never clobbered to NULL).
             */
            display_name?: string | null;
            /** @description The `(epoch, seq)` this publish's compare-and-set targets; a stale pair yields `CONFLICT`. */
            expected: components["schemas"]["Generation"];
            /** @description The client-minted UUIDv4 idempotency key — the same `op_id` replays the stored receipt byte-for-byte. */
            op_id: string;
            /** @description The target skill id within the workspace. */
            skill_id: string;
            /** @description The target workspace id (the receipt + pointer scope). */
            workspace_id: string;
        };
        /**
         * @description The ONE canonical receipt across all outcomes — the durable idempotency record (present even
         *     on failures): one stable receipt per op, identical on retry.
         */
        Receipt: {
            /** @description The byte-exact consent hash (lowercase hex). */
            bundle_digest?: string | null;
            command: string;
            /** @description RFC 3339 timestamp (the plane stamps it; never an ambient clock in `topos-core`). */
            created_at: string;
            current_generation?: null | components["schemas"]["Generation"];
            /** @description Outcome-specific extra detail. */
            details?: unknown;
            expected_generation?: null | components["schemas"]["Generation"];
            /** @description Client-minted UUIDv4, persisted before the first send. */
            op_id: string;
            outcome: components["schemas"]["TerminalOutcome"];
            /**
             * Format: int32
             * @description Always `1` for this contract version (the schema pins it `const`).
             */
            schema_version: number;
            skill_id?: string | null;
            /** @description The commit SHA-256 (lowercase hex). */
            version_id?: string | null;
            workspace_id: string;
        };
        /**
         * @description `POST /v1/workspaces/{ws}/devices` body — redeem an enrollment grant into a registered device + its
         *     ONE minted workspace credential. The server checks `device_public_key` equals the grant's bound key
         *     (a binding check) and re-derives the device key id from it.
         */
        RedeemRequest: {
            /** @description The device's raw 32-byte public key, base64url-unpadded (must equal the grant's bound key). */
            device_public_key: string;
            /** @description The opaque single-use enrollment grant (from a `granted` device-token poll). */
            grant: string;
            /** @description The workspace the device enrolls into (authoritatively the grant's; echoed for the client's clarity). */
            workspace_id: string;
        };
        /**
         * @description `POST /v1/workspaces/{ws}/devices` success payload — the confirmed enrollment: the registered device
         *     and its ONE workspace credential (the `0600` at-rest secret this device presents on every read and
         *     write in this workspace). **NO user token, ever; no per-skill token, ever.** Rides in the all-outcome
         *     envelope's `data`.
         */
        RedeemResponse: {
            /**
             * @description The plaintext workspace credential (returned ONCE; only its sha256 is stored server-side, on the
             *     device's registry row). No expiry — revocation is a directory row-write, re-enrollment the rotation.
             */
            credential: string;
            /**
             * @description The server-derived device key id now registered (the device's stable, non-secret name — the
             *     receipts/audit actor; never an authenticator).
             */
            device_key_id: string;
            /**
             * @description The principal the device now acts as (the confirmed email, or a device-rooted id) — a disclosure the
             *     client persists and prints so a hijacked standup is visible ("workspace X — owner Y").
             */
            principal?: string | null;
            /** @description The workspace the device enrolled into. */
            workspace_id: string;
        };
        /**
         * @description `revert` (a **forward** git-revert restoring older bytes as a new, higher-`seq` version — never a
         *     pointer rollback, never a delete). `--to` names the GOOD version. **INFERRED.**
         */
        RevertData: {
            current_generation: components["schemas"]["Generation"];
            /** @description The new forward-revert commit that carries those bytes. */
            new_version_id: string;
            /** @description The good version named by `--to` (the bytes being restored). */
            reverted_to: string;
            skill_id: string;
        };
        /**
         * @description `POST /v1/reverts` body — a **forward** revert: the server constructs a new 1-parent commit carrying the
         *     `good` version's bytes on top of `current` (`seq` advances; the pointer never moves backward). There is
         *     **no candidate** — the server reads `good`'s tree + digest from its provenance and builds the commit.
         */
        RevertRequest: {
            /** @description The author device id recorded in the forward-revert commit frame. */
            author: string;
            /** @description The `(epoch, seq)` this revert's compare-and-set targets; a stale pair yields `CONFLICT`. */
            expected: components["schemas"]["Generation"];
            /** @description The GOOD version (the `version_id` whose bytes are restored) as 64-char lowercase hex. */
            good: string;
            /** @description The forward-revert commit message. */
            message: string;
            /** @description The client-minted UUIDv4 idempotency key (replays the stored receipt on retry). */
            op_id: string;
            /** @description The target skill id within the workspace. */
            skill_id: string;
            /** @description The target workspace id. */
            workspace_id: string;
        };
        /**
         * @description `review` (`--approve` / `--reject` a proposal). Approve is a compare-and-set on the base; a stale
         *     base returns `CONFLICT`. **INFERRED.**
         */
        ReviewData: {
            current_generation?: null | components["schemas"]["Generation"];
            decision: components["schemas"]["ReviewDecision"];
            /** @description `<skill>@<version_id>` of the reviewed proposal. */
            proposal: string;
        };
        /**
         * @description A review verdict — `approve` promotes, `reject` carries a reason back, `withdraw` is the author
         *     retracting their own open proposal. **INFERRED.**
         * @enum {string}
         */
        ReviewDecision: "approve" | "reject" | "withdraw";
        /**
         * @description `POST /v1/reviews` body — a governance decision on an open proposal. `approve` runs the shared
         *     `(epoch, seq)` compare-and-set on the proposal's base (a stale base ⇒ `CONFLICT`) and, under
         *     `review_required`, enforces four-eyes (the proposer may not self-approve) before promoting; `reject`
         *     is a standalone status flip (no pointer move).
         */
        ReviewRequest: {
            /**
             * @description The verdict — `approve` (promote), `reject` (with its reason), or `withdraw` (the author
             *     retracting their own open proposal).
             */
            decision: components["schemas"]["ReviewDecision"];
            /**
             * @description The `(epoch, seq)` the approval's compare-and-set targets (the proposal's base); a stale pair on an
             *     `approve` yields `CONFLICT`.
             */
            expected: components["schemas"]["Generation"];
            /** @description The client-minted UUIDv4 idempotency key (replays the stored receipt on retry). */
            op_id: string;
            /** @description The proposal being reviewed, named by its candidate commit id (64-char lowercase hex). */
            proposal: string;
            /** @description The reject's reason, carried back to the author (REQUIRED on `reject`; absent otherwise). */
            reason?: string | null;
            /** @description The target skill id within the workspace. */
            skill_id: string;
            /** @description The target workspace id. */
            workspace_id: string;
        };
        /**
         * @description `DELETE /v1/workspaces/{ws}/roster/{email}` body — remove a principal from the workspace roster
         *     (owner-only). The target principal is the `{email}` path segment; the body carries only the op identity.
         */
        RosterRemoveRequest: {
            /** @description The client-minted UUIDv4 idempotency key. */
            op_id: string;
            /** @description The target workspace id (scopes the op to one workspace). */
            workspace_id: string;
        };
        /**
         * @description `PUT /v1/workspaces/{ws}/roster/{email}` body — set a principal's workspace role (owner-only). The target
         *     principal is the `{email}` path segment; the role rides the body.
         */
        RosterSetRequest: {
            /** @description The client-minted UUIDv4 idempotency key. */
            op_id: string;
            /** @description The role to set on the `{email}` target. */
            role: components["schemas"]["WorkspaceRole"];
            /** @description The target workspace id (scopes the op to one workspace). */
            workspace_id: string;
        };
        /**
         * @description A device-auth session's intent — a CLOSED set (snake_case). `enroll` joins an existing workspace named
         *     by its ADDRESS; `standup` starts with NO workspace (a signed-in human's approval creates one and seats
         *     the approver as its first owner); `login` proves the person's identity and re-mints this device's
         *     workspace credentials.
         * @enum {string}
         */
        SessionIntent: "enroll" | "standup" | "login";
        /**
         * @description The standup disclosure a workspace-creating publish carries: which workspace was stood up and who owns
         *     it. **INFERRED.**
         */
        StandupReceipt: {
            /** @description The stood-up workspace's ADDRESS (the share link — printed once at genesis, pasted anywhere). */
            address?: string | null;
            /**
             * @description The seated owner principal (the approver's confirmed email, or a device-rooted id) — the hijack
             *     tripwire: a principal you don't recognize means someone else approved (and owns) this workspace.
             */
            owner_principal?: string | null;
            /** @description The stood-up workspace's display name (chosen at the sign-in approval). */
            workspace_display_name: string;
        };
        /**
         * @description The closed set of terminal outcomes the agent branches on. SCREAMING_SNAKE on the wire.
         * @enum {string}
         */
        TerminalOutcome: "OK" | "NEEDS_REVIEW" | "CONFLICT" | "DIVERGED" | "DENIED" | "UNAVAILABLE" | "AMBIGUOUS_NAME" | "RETRYABLE_FAILURE" | "PERMANENT_FAILURE";
        /**
         * @description `GET /v1/enroll/verify/{user_code}` response — the verification-page disclosure a human reviews before
         *     confirming an identity (the RFC-8628 confused-deputy guard). Carries no secret.
         */
        VerificationContextResponse: {
            /**
             * @description A short hex fingerprint of the device's public key — a human cross-checks it against the device. A
             *     display aid only, never an authority input.
             */
            device_fingerprint: string;
            intent?: null | components["schemas"]["SessionIntent"];
            /** @description The human-readable machine name the device offered at start. */
            machine_name: string;
            /** @description The skills the invite pre-offers (each with an optional display name). */
            offered_skills?: components["schemas"]["BootstrapSkill"][];
            /** @description The org-domain claim, if any. */
            verified_domain?: string | null;
            /** @description The domain-verification state. */
            verified_domain_status: components["schemas"]["VerifiedDomainStatus"];
            /** @description The workspace display name the device would join. */
            workspace_display_name: string;
        };
        /**
         * @description A workspace's domain-verification state — snake_case on the wire.
         * @enum {string}
         */
        VerifiedDomainStatus: "unverified" | "pending" | "verified";
        /**
         * @description `PUT /v1/workspaces/{ws}/report` body — the fleet's applied-state report: this device's
         *     `(skill, applied version)` snapshot after a reconcile. The plane upserts the snapshot, drops the
         *     non-detached rows it no longer names, and stamps the staleness clock (last-writer-wins; no receipt).
         *     The acting device rides the `Authorization: Bearer` workspace credential, never a body field.
         */
        WireAppliedReport: {
            /** @description The device's applied skills (possibly empty — a device holding nothing reports an empty list). */
            applied: components["schemas"]["WireAppliedSkill"][];
            /**
             * Format: int32
             * @description Always `1` for this contract version (the schema pins it `const`).
             */
            schema_version: number;
        };
        /**
         * @description One applied-state row a device reports: the skill and the version it currently holds after its
         *     reconcile.
         */
        WireAppliedSkill: {
            /** @description The skill id (the `<skill>` path segment). */
            skill_id: string;
            /** @description The version this device holds (64-char lowercase hex). */
            version_id: string;
        };
        /**
         * @description A full candidate bundle: every file's bytes, the declared parents, and the author + message — the
         *     shared input the `publish` and `propose` writes ingest (the `revert` write needs no candidate; the
         *     server builds that forward commit from the good version). Maps to `plane-store`'s
         *     `CandidateUpload { files, parents, author, message }` — each `parents` entry hex-decoded into a
         *     `CommitId`.
         */
        WireCandidate: {
            /** @description The author device id recorded in the commit frame. */
            author: string;
            /** @description Every file in the candidate bundle (each server-rehashed). */
            files: components["schemas"]["WireFile"][];
            /** @description The commit message (title + body composed into one string). */
            message: string;
            /**
             * @description The candidate commit's declared parents, each a 64-char lowercase-hex `version_id` (`0` parents for a
             *     genesis publish, `1` for a normal publish / propose, `2` for an author merge). Each must already be
             *     present in the workspace; a lie changes the recomputed commit id, so the server need not trust it.
             */
            parents: string[];
        };
        /** @description One channel in the workspace's channel index. */
        WireChannelEntry: {
            /** @description Whether this is the structural `everyone` (roster-derived membership; cannot be joined or left). */
            builtin: boolean;
            /** @description Whether the CALLER is a member (always `true` on `everyone`). */
            member: boolean;
            /**
             * Format: int64
             * @description How many people the channel reaches (confirmed roster size for `everyone`).
             */
            member_count: number;
            /** @description The channel's mode (`open` or `curated`). */
            mode: string;
            /** @description The channel's name. */
            name: string;
            /** @description The skills the channel references. */
            skills: components["schemas"]["WireChannelSkill"][];
        };
        /**
         * @description `GET /v1/workspaces/{ws}/channels` response — the workspace's channels with the caller's own
         *     membership marked. Member-scoped.
         */
        WireChannelIndex: {
            /** @description The channels (the structural `everyone` always present). */
            channels: components["schemas"]["WireChannelEntry"][];
        };
        /** @description One skill reference inside a channel entry. */
        WireChannelSkill: {
            /** @description The skill's catalog name. */
            name: string;
            /** @description The referenced skill id. */
            skill_id: string;
        };
        /**
         * @description The `current` pointer's wire body — the UNSIGNED document the plane serves at the pointer read,
         *     embeds in OK receipts, and stores. It is unsigned: authority is the database row behind the pointer,
         *     and integrity is the content-addressed `version_id` re-verified byte-for-byte on apply. A versioned
         *     envelope; `ETag = "<epoch>.<seq>"`.
         */
        WireCurrentRecord: {
            record: components["schemas"]["CurrentRecord"];
            /**
             * Format: int32
             * @description Always `1` for this contract version (the schema pins it `const`).
             */
            schema_version: number;
            scope: components["schemas"]["PointerScope"];
        };
        /**
         * @description `GET /v1/workspaces/{ws}/delivery` response body — the currency answer for ONE enrolled device: the
         *     entitled skills (what this device should have), the person's detached skills (freeze-in-place, never
         *     cleaned), the unacked notices feed, and the open-proposal count across the entitled set. The
         *     session-start hook fetches it once per workspace and reconciles the harness against it, silently. A
         *     versioned envelope.
         */
        WireDelivery: {
            /**
             * @description The skill ids the person detached (unfollowed, or lapsed via a channel leave / removal) and that are
             *     NOT currently re-entitled — every device freezes these in place, never cleaning them.
             */
            detached: string[];
            /**
             * @description The skill ids THIS DEVICE excludes ("not on this device") — the third actor in the who-acts
             *     split, alongside the person (`detached`) and upstream (absent from `skills` entirely). The copy
             *     leaves this device; the person keeps receiving it on every other device; `follow` here lifts it.
             *     Sent so the client narrates the true CAUSE instead of mistaking an exclusion written elsewhere
             *     (the web, a second tool) for an upstream withdrawal.
             */
            excluded?: string[];
            /** @description The unacked, person-scoped notices (verdicts, proposal closures, …). */
            notices: components["schemas"]["WireNotice"][];
            /**
             * Format: int64
             * @description The count of OPEN, non-stale proposals across the entitled skills (the review-inbox pressure gauge).
             */
            proposals_awaiting: number;
            /**
             * Format: int32
             * @description Always `1` for this contract version (the schema pins it `const`).
             */
            schema_version: number;
            /** @description The entitled skills — everything this device should have (a possibly-empty list). */
            skills: components["schemas"]["WireDeliverySkill"][];
            /**
             * Format: int64
             * @description The workspace's staleness window (epoch milliseconds) — the ONE clock the fleet page and the
             *     client's hook warning both read: a device whose last report is older than this is stale.
             *     Additive: an older producer that omits it falls back to the one-week default (a whole delivery
             *     body must never fail to parse over one new field).
             */
            staleness_window_ms?: number;
            /** @description The workspace this delivery is scoped to (echoed from the path). */
            workspace_id: string;
        };
        /**
         * @description One skill THIS device should have, in the delivery answer: the catalog identity, the pinned `current`
         *     version + its consent digest, the resolved protection posture, and the `via` attribution. **NO bytes** —
         *     after reconciling the client fetches each version through the per-blob bundle read.
         */
        WireDeliverySkill: {
            /** @description The `current` byte-exact consent hash (64-char lowercase hex) — the fetch + re-hash pin. */
            bundle_digest: string;
            /** @description The unsigned, advisory display name (the author's folder name); absent ⇒ show `name`. */
            display_name?: string | null;
            /** @description The `current` pointer's `(epoch, seq)`. */
            generation: components["schemas"]["Generation"];
            /** @description The catalog's user-facing name (the on-disk directory name for a fresh install). */
            name: string;
            /**
             * @description The resolved per-bundle protection posture — `"open"` or `"reviewed"` (the client's publish
             *     preflight; the server re-decides authoritatively on every write). An OPEN string for forward
             *     compat — a client treats an unrecognized value as the stricter posture.
             */
            protection: string;
            /** @description The skill id (the `<skill>` path segment). */
            skill_id: string;
            /**
             * Format: int64
             * @description When `current` last moved (epoch milliseconds).
             */
            updated_at: number;
            /** @description The pinned `current` version's commit id (64-char lowercase hex). */
            version_id: string;
            /** @description Why this device is entitled to the skill (channels ∪ direct). */
            via: components["schemas"]["WireVia"];
        };
        /**
         * @description The flat wire error (rich `thiserror` enums stay internal). Carries a
         *     stable code + retryability + the safe next actions; never raw SQL/git strings.
         */
        WireError: {
            affected?: components["schemas"]["Affected"];
            /**
             * @description A stable, machine-branchable error code, distinct from (and finer than) `outcome`. This is an
             *     **open, additive** string vocabulary — it is intentionally NOT a closed enum: new codes are
             *     added over time, and a consumer must treat an unrecognized `code` as the `outcome` it carries.
             */
            code: string;
            /** @description Structured context (no TTY prose to parse). */
            context?: unknown;
            current_generation?: null | components["schemas"]["Generation"];
            expected_generation?: null | components["schemas"]["Generation"];
            next_actions?: components["schemas"]["NextAction"][];
            outcome: components["schemas"]["TerminalOutcome"];
            retryable: boolean;
        };
        /**
         * @description One file of a candidate bundle, uploaded **by value**. The raw bytes ride as base64 in the JSON body
         *     (`content_base64`, standard alphabet); the server base64-decodes them and **rehashes every byte** to
         *     derive the content id — there is no reference-by-id, and a client hash is never trusted. Maps to
         *     `plane-store`'s `UploadedFile { path, mode, bytes }` (decode `content_base64` → `bytes`).
         */
        WireFile: {
            /** @description The raw file bytes, base64-encoded. The server decodes then rehashes them (server-side digest). */
            content_base64: string;
            /** @description The file mode (regular or executable). */
            mode: components["schemas"]["WireFileMode"];
            /** @description The bundle-relative, forward-slash path. */
            path: string;
        };
        /**
         * @description A candidate file's mode on the wire — the two git regular-file modes as their literal octal strings
         *     (`"100644"` / `"100755"`). A **closed** wire mirror of `topos_core::digest::FileMode`: that kernel enum
         *     lives in a `no_std` crate `topos-types` does not depend on (and it carries no serde/schema derives), so
         *     the wire leaf owns its own copy. The route handler maps it 1:1 at the edge —
         *     `Regular ⇔ FileMode::Regular`, `Executable ⇔ FileMode::Executable` — for both the inbound candidate
         *     ([`WireFile`]) and the outbound version metadata ([`WireVersionFile`]).
         * @enum {string}
         */
        WireFileMode: "100644" | "100755";
        /** @description One proposal event in a skill's history (open, and every resolution). */
        WireLogProposal: {
            /** @description When the proposal was opened (server-stamped string). */
            created_at: string;
            /** @description The author's principal. */
            proposer: string;
            /** @description When it was resolved (server-stamped string), when resolved. */
            resolved_at?: string | null;
            /** @description Who resolved it, when resolved. */
            resolved_by?: string | null;
            /** @description The resolution reason (a reject's rationale; a closure's cause), when recorded. */
            resolved_reason?: string | null;
            /** @description The proposal's status (`open` / `accepted` / `rejected` / `closed`). */
            status: string;
            /** @description The proposed version's commit id (64-char lowercase hex). */
            version_id: string;
        };
        /**
         * @description One version in a skill's history. A PURGED version stays listed — who purged it and when — with its
         *     bytes gone (author/message may be absent once the underlying objects are reclaimed).
         */
        WireLogVersion: {
            /** @description The version author, when the commit object is still readable. */
            author?: string | null;
            /** @description Whether this version is the skill's `current`. */
            current: boolean;
            /** @description The version message, when the commit object is still readable. */
            message?: string | null;
            /**
             * Format: int64
             * @description When the version's bytes were purged (epoch milliseconds) — the tombstone half.
             */
            purged_at?: number | null;
            /** @description Who purged the version's bytes — the tombstone half. */
            purged_by?: string | null;
            /** @description The version's commit id (64-char lowercase hex). */
            version_id: string;
        };
        /**
         * @description `GET /v1/workspaces/{ws}/me` response — the caller's own membership describe: who you are here,
         *     who added you, and the workspace's address block. Member-scoped (the uniform not-found otherwise).
         */
        WireMe: {
            /** @description The workspace's full address (the share link — server-built on the public link base). */
            address: string;
            /** @description The workspace's display name. */
            display_name: string;
            /** @description The workspace's invite policy (`members` or `owners`). */
            invite_policy: string;
            /** @description Who invited this principal (absent for a genesis owner). */
            invited_by?: string | null;
            /** @description The workspace's ADDRESS name. */
            name: string;
            /** @description The caller's principal (canonical form). */
            principal: string;
            /** @description The caller's role (`owner` / `reviewer` / `member`). */
            role: string;
            /** @description The workspace id. */
            workspace_id: string;
        };
        /**
         * @description One unacked, person-scoped notice in the delivery feed. `kind` is an OPEN vocabulary that grows without
         *     a schema break (today's values include `"verdict"` and `"proposal_closed"`); every other field is
         *     present only when the notice names it. The silent currency hook fetches these without acking; an
         *     interactive surface acks by id.
         */
        WireNotice: {
            /** @description The actor whose action raised the notice, when recorded. */
            actor?: string | null;
            /** @description When the notice was created (the server-stamped RFC-3339 string). */
            created_at: string;
            /** @description The notice id (the ack handle). */
            id: string;
            /**
             * @description The notice kind — an OPEN vocabulary (e.g. `"verdict"`, `"proposal_closed"`); a client ignores a
             *     kind it does not recognize.
             */
            kind: string;
            /** @description A rendered human message, when the notice carries one. */
            message?: string | null;
            /** @description The outcome (e.g. a verdict's `approve` / `reject`), when recorded. */
            outcome?: string | null;
            /** @description The human reason (a review's rationale), when recorded. */
            reason?: string | null;
            /** @description The skill the notice concerns, when it names one. */
            skill_id?: string | null;
            /** @description The skill's current catalog name (joined for narration), when the notice names a skill. */
            skill_name?: string | null;
            /** @description The version the notice concerns (64-char lowercase hex), when it names one. */
            version_id?: string | null;
        };
        /**
         * @description One OPEN proposal on the wire — its candidate `version_id` (the `@hash`), the `base_generation` it was
         *     opened against, and when. The proposals-listing read returns ONLY these three fields: **no bytes, no
         *     proposer, no roles, no rendered diff**. Mirrors `plane-store`'s `OpenProposalSummary` with the id hex-encoded.
         */
        WireOpenProposal: {
            /**
             * @description The `(epoch, seq)` the proposal was opened against (its base); when `current` advances past it the
             *     proposal stales and drops out of this list.
             */
            base_generation: components["schemas"]["Generation"];
            /** @description When the proposal was opened (the server-stamped RFC-3339 string). */
            created_at: string;
            /** @description The proposal's candidate commit id (64-char lowercase hex) — the `<skill>@<version_id>` handle. */
            version_id: string;
        };
        /** @description One open proposal in the workspace's review inbox. */
        WireProposalEntry: {
            /** @description The base version the proposal was built on (64-char lowercase hex). */
            base_version_id: string;
            /** @description When the proposal was opened (the server-stamped string). */
            created_at: string;
            /** @description The author's message (the proposed version's commit message) — what a reviewer reads FIRST. */
            message: string;
            /** @description The author's principal. */
            proposer: string;
            /** @description The skill the proposal targets. */
            skill_id: string;
            /** @description The skill's catalog name. */
            skill_name: string;
            /** @description Whether `current` has moved since the proposal's base (a stale proposal needs a re-propose). */
            stale: boolean;
            /** @description The proposed version's commit id (64-char lowercase hex) — the review target handle. */
            version_id: string;
        };
        /**
         * @description `GET /v1/workspaces/{ws}/proposals` response — every OPEN proposal in the workspace, author-message
         *     first. The caller splits inbox (others') from outbox (own) by `proposer`. Member-scoped.
         */
        WireProposalIndex: {
            /** @description The open proposals (possibly empty). */
            proposals: components["schemas"]["WireProposalEntry"][];
        };
        /**
         * @description `GET /v1/workspaces/{ws}/skills/{skill}/proposals` response body — the OPEN, non-stale proposals on a
         *     rostered skill (a possibly-empty list, ordered by `(created_at, version_id)`). A staled proposal is absent
         *     (keep == read == list); the list carries no bytes and no proposer — it is the thin handle a client turns
         *     into a `diff` / `review` follow-up.
         */
        WireProposalList: {
            /** @description The open proposals (possibly empty). */
            proposals: components["schemas"]["WireOpenProposal"][];
        };
        /**
         * @description The MACHINE face of the constant protocol card — what an `Accept: application/json` GET of any
         *     resource address returns, identical for every path (no content, no existence signal): just enough
         *     for a client to re-root onto the API and run `follow`.
         */
        WireProtocolCard: {
            /** @description The API base URL the client re-roots onto (the origin serving `/v1`). */
            api_base_url: string;
            /** @description The constant discriminant a client dispatches on (`"topos-protocol-card"`). */
            card: string;
            /**
             * Format: int32
             * @description Always `1` for this contract version (the schema pins it `const`).
             */
            schema_version: number;
        };
        /**
         * @description `GET /v1/workspaces/{ws}/skills/{skill}/reach` response — the audience a change to this skill
         *     reaches (the describe number behind `publish` and `protect`). Member-scoped.
         */
        WireReach: {
            /**
             * Format: int64
             * @description How many registered, non-revoked devices those people hold here.
             */
            devices: number;
            /**
             * Format: int64
             * @description How many people are entitled to the skill.
             */
            persons: number;
        };
        /**
         * @description `GET /v1/workspaces/{ws}/skills` response body — the workspace catalog (every skill holding a `current`),
         *     authorized by workspace membership (the `Authorization: Bearer` workspace credential names the
         *     device; catalog
         *     visibility == membership, on both cloud and self-host). Metadata only, no bytes; a possibly-empty list
         *     ordered by `skill_id`.
         */
        WireSkillIndex: {
            /** @description The workspace's skills (possibly empty). */
            skills: components["schemas"]["WireSkillIndexEntry"][];
        };
        /**
         * @description One skill of the workspace catalog, as `GET /v1/workspaces/{ws}/skills` returns it: the discovery
         *     metadata a member browses to decide what to follow — **NO bytes**. Mirrors `plane-store`'s
         *     `SkillIndexRow` with every 32-byte id hex-encoded.
         */
        WireSkillIndexEntry: {
            /** @description The `current` byte-exact consent hash (64-char lowercase hex). */
            bundle_digest: string;
            /** @description The unsigned, advisory folder display name (may be absent). */
            display_name?: string | null;
            /** @description The `current` pointer's `(epoch, seq)`. */
            generation: components["schemas"]["Generation"];
            /** @description The catalog's user-facing name (a pre-catalog seeded pointer falls back to the skill id). */
            name: string;
            /**
             * Format: int64
             * @description The count of OPEN, non-stale proposals on the skill.
             */
            open_proposals: number;
            /** @description The skill id (the `<skill>` path segment). */
            skill_id: string;
            /**
             * @description The catalog lifecycle status — `"active"` / `"archived"` (a deleted skill has no `current` row and
             *     so no entry). An OPEN string, deliberately: a new state can land without a schema break.
             */
            status: string;
            /**
             * Format: int64
             * @description When `current` last moved (epoch milliseconds).
             */
            updated_at: number;
            /** @description The `current` version's commit id (64-char lowercase hex). */
            version_id: string;
        };
        /**
         * @description `GET /v1/workspaces/{ws}/skills/{skill}/log` response — the skill's version history (purge
         *     tombstones included) and its proposal events. An ARCHIVED skill stays addressable here; asking by a
         *     freed base name answers the archived successor as a hint. Member-scoped.
         */
        WireSkillLog: {
            /** @description The pre-archive name, when archived (what the skill was called before the rename freed it). */
            base_name?: string | null;
            /** @description The skill's current catalog name (the archived spelling once archived). */
            name: string;
            /** @description The proposal events, newest first. */
            proposals: components["schemas"]["WireLogProposal"][];
            /** @description The skill id. */
            skill_id: string;
            /** @description The skill's lifecycle status (`active` / `archived` / `deleted`). */
            status: string;
            /**
             * @description The versions, newest first where orderable (the ancestry walk stops at reclaimed history;
             *     tombstoned leftovers follow unordered).
             */
            versions: components["schemas"]["WireLogVersion"][];
        };
        /**
         * @description One file of a version's metadata on the wire — its path, mode, and content id (`object_id`), mirroring
         *     `plane-store`'s `VersionFile` with the id hex-encoded. The **bytes are NOT here**: a client fetches each
         *     by `object_id` through the bundle (object) read route.
         */
        WireVersionFile: {
            /** @description The file mode (regular or executable). */
            mode: components["schemas"]["WireFileMode"];
            /** @description The file's content id (64-char lowercase hex) — the handle the per-blob read route resolves. */
            object_id: string;
            /** @description The bundle-relative, forward-slash path. */
            path: string;
        };
        /**
         * @description `GET /v1/workspaces/{ws}/skills/{skill}/versions/{version_id}` response body — a version's authenticated
         *     metadata: its id, the COMPLETE parent set, display author + message, the consent `bundle_digest`, and the
         *     per-file `(path, mode, object_id)` leaves. Mirrors `plane-store`'s `VersionMeta` with every 32-byte id
         *     hex-encoded. Assembled WITHOUT reading any blob bytes; the `bundle_digest` is the pin the client's
         *     per-blob fetches + its own re-hash must reproduce.
         */
        WireVersionMeta: {
            /** @description The author device id from the commit frame. */
            author: string;
            /** @description The byte-exact consent hash over the bundle (64-char lowercase hex) — the fetch + re-hash pin. */
            bundle_digest: string;
            /** @description The per-file leaves, in the version's recorded order. */
            files: components["schemas"]["WireVersionFile"][];
            /** @description The commit message (title + body as one string). */
            message: string;
            /**
             * @description The COMPLETE parent set, each a 64-char lowercase-hex commit id (`0` for genesis, `1` normally, `2`
             *     for an author merge).
             */
            parents: string[];
            /** @description This version's commit id (64-char lowercase hex). */
            version_id: string;
        };
        /**
         * @description Why THIS device is entitled to a delivered skill — the attribution the client's narration reads. A
         *     delivered skill always has at least one of the two: it rides one or more channels, and/or the person
         *     follows it directly (a direct follow survives every channel drop).
         */
        WireVia: {
            /** @description The channels delivering the skill (names, sorted; `everyone` is present when it delivers). */
            channels: string[];
            /** @description Whether the person also follows the skill directly (independent of any channel). */
            direct: boolean;
        };
        /**
         * @description A workspace-level governance role (the RBAC roster — DISTINCT from the per-skill read roster). snake_case.
         * @enum {string}
         */
        WorkspaceRole: "owner" | "reviewer" | "member";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_verification_context: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user code shown by `device/authorize`. */
                user_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The verification-page disclosure (machine name, fingerprint, workspace, offered skills). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationContextResponse"];
                };
            };
            /** @description No live session for that user code. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JsonEnvelope"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JsonEnvelope"];
                };
            };
            /** @description Internal store fault. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JsonEnvelope"];
                };
            };
        };
    };
}
