/**
 * Generated by scripts/gen-plane-types.mjs from ../Cargo.toml — do not edit.
 * Regenerate with: bun run gen:plane
 */

/** The release version of the build serving this app — what the protocol card declares. */
export const SERVER_RELEASE_VERSION = "0.1.36";
