/**
 * Generated by scripts/gen-plane-types.mjs from ../Cargo.toml + ../contracts/openapi/openapi.json
 * — do not edit. Regenerate with: bun run gen:plane
 */

/** The release version of the build serving this app — what the protocol card declares. */
export const SERVER_RELEASE_VERSION = "0.1.55";

/** The wire contract's version — stamped on every document this tier emits. */
export const WIRE_SCHEMA_VERSION = 2;

/**
 * The versions this tier still READS on the way in. A deployed client speaks the version it
 * was built with, and the min-CLI floor admits releases older than this contract — so the
 * door accepts those too, or a deploy would refuse every machine in the field.
 */
export const ACCEPTED_WIRE_SCHEMA_VERSIONS: readonly number[] = [1, 2];
